[2023-03-07T08:06:41.900+0000] {processor.py:153} INFO - Started process (PID=9838) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:06:41.901+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:06:41.902+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:06:41.902+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:06:41.932+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:06:41.931+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:06:41.933+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:06:41.955+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.059 seconds
[2023-03-07T08:07:12.182+0000] {processor.py:153} INFO - Started process (PID=9867) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:07:12.183+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:07:12.184+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:07:12.184+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:07:12.215+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:07:12.214+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:07:12.216+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:07:12.240+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.062 seconds
[2023-03-07T08:07:42.398+0000] {processor.py:153} INFO - Started process (PID=9907) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:07:42.400+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:07:42.401+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:07:42.401+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:07:42.430+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:07:42.429+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:07:42.430+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:07:42.452+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.059 seconds
[2023-03-07T08:08:12.681+0000] {processor.py:153} INFO - Started process (PID=9935) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:08:12.682+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:08:12.683+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:08:12.683+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:08:12.714+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:08:12.713+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:08:12.715+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:08:12.736+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.059 seconds
[2023-03-07T08:08:43.001+0000] {processor.py:153} INFO - Started process (PID=9973) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:08:43.003+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:08:43.004+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:08:43.004+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:08:43.043+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:08:43.042+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:08:43.043+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:08:43.071+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.084 seconds
[2023-03-07T08:09:13.298+0000] {processor.py:153} INFO - Started process (PID=10002) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:09:13.299+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:09:13.300+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:09:13.300+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:09:13.328+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:09:13.327+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:09:13.329+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:09:13.349+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.055 seconds
[2023-03-07T08:09:43.619+0000] {processor.py:153} INFO - Started process (PID=10028) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:09:43.621+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:09:43.622+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:09:43.621+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:09:43.649+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:09:43.648+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:09:43.650+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:09:43.670+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.055 seconds
[2023-03-07T08:10:13.964+0000] {processor.py:153} INFO - Started process (PID=10067) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:10:13.965+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:10:13.966+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:10:13.966+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:10:13.994+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:10:13.993+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:10:13.994+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:10:14.018+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.058 seconds
[2023-03-07T08:10:44.282+0000] {processor.py:153} INFO - Started process (PID=10095) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:10:44.283+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:10:44.284+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:10:44.284+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:10:44.312+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:10:44.311+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:10:44.312+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:10:44.333+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.055 seconds
[2023-03-07T08:11:14.593+0000] {processor.py:153} INFO - Started process (PID=10131) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:11:14.595+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:11:14.596+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:11:14.595+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:11:14.636+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:11:14.635+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:11:14.636+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:11:14.664+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.076 seconds
[2023-03-07T08:11:44.921+0000] {processor.py:153} INFO - Started process (PID=10164) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:11:44.923+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:11:44.924+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:11:44.924+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:11:44.955+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:11:44.954+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:11:44.955+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:11:44.976+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.060 seconds
[2023-03-07T08:12:15.238+0000] {processor.py:153} INFO - Started process (PID=10193) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:12:15.239+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:12:15.240+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:12:15.240+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:12:15.271+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:12:15.270+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:12:15.272+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:12:15.293+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.061 seconds
[2023-03-07T08:12:45.590+0000] {processor.py:153} INFO - Started process (PID=10233) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:12:45.591+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:12:45.592+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:12:45.592+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:12:45.621+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:12:45.620+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:12:45.621+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:12:45.642+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.056 seconds
[2023-03-07T08:13:15.914+0000] {processor.py:153} INFO - Started process (PID=10260) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:13:15.916+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:13:15.917+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:13:15.917+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:13:15.947+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:13:15.946+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:13:15.947+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:13:15.967+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.057 seconds
[2023-03-07T08:13:46.223+0000] {processor.py:153} INFO - Started process (PID=10294) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:13:46.225+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:13:46.226+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:13:46.226+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:13:46.269+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:13:46.267+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:13:46.269+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:13:46.299+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.081 seconds
[2023-03-07T08:14:16.514+0000] {processor.py:153} INFO - Started process (PID=10326) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:14:16.515+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:14:16.516+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:14:16.516+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:14:16.545+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:14:16.544+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:14:16.545+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:14:16.567+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.058 seconds
[2023-03-07T08:14:46.852+0000] {processor.py:153} INFO - Started process (PID=10355) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:14:46.853+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:14:46.854+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:14:46.853+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:14:46.888+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:14:46.886+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:14:46.888+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:14:46.910+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.063 seconds
[2023-03-07T08:15:17.195+0000] {processor.py:153} INFO - Started process (PID=10396) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:15:17.197+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:15:17.199+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:15:17.198+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:15:17.233+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:15:17.232+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:15:17.233+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:15:17.258+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.069 seconds
[2023-03-07T08:15:47.489+0000] {processor.py:153} INFO - Started process (PID=10424) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:15:47.490+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:15:47.491+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:15:47.490+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:15:47.519+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:15:47.518+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:15:47.519+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:15:47.541+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.057 seconds
[2023-03-07T08:16:17.813+0000] {processor.py:153} INFO - Started process (PID=10462) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:16:17.823+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:16:17.825+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:16:17.824+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:16:17.865+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:16:17.864+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:16:17.866+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:16:17.894+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.087 seconds
[2023-03-07T08:16:48.050+0000] {processor.py:153} INFO - Started process (PID=10492) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:16:48.051+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:16:48.052+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:16:48.052+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:16:48.083+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:16:48.082+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:16:48.083+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:16:48.106+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.062 seconds
[2023-03-07T08:17:18.329+0000] {processor.py:153} INFO - Started process (PID=10518) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:17:18.331+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:17:18.332+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:17:18.332+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:17:18.362+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:17:18.361+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:17:18.362+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:17:18.383+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.059 seconds
[2023-03-07T08:17:48.695+0000] {processor.py:153} INFO - Started process (PID=10555) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:17:48.696+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:17:48.696+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:17:48.696+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:17:48.727+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:17:48.726+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:17:48.727+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:17:48.749+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.059 seconds
[2023-03-07T08:18:19.014+0000] {processor.py:153} INFO - Started process (PID=10582) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:18:19.016+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:18:19.017+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:18:19.017+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:18:19.045+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:18:19.044+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:18:19.046+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:18:19.066+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.058 seconds
[2023-03-07T08:18:49.311+0000] {processor.py:153} INFO - Started process (PID=10610) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:18:49.312+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:18:49.313+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:18:49.313+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:18:49.353+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:18:49.352+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:18:49.353+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:18:49.381+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.075 seconds
[2023-03-07T08:19:19.526+0000] {processor.py:153} INFO - Started process (PID=10652) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:19:19.527+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:19:19.528+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:19:19.528+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:19:19.557+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:19:19.556+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:19:19.558+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:19:19.581+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.060 seconds
[2023-03-07T08:19:49.857+0000] {processor.py:153} INFO - Started process (PID=10678) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:19:49.858+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:19:49.859+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:19:49.859+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:19:49.887+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:19:49.886+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:19:49.888+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:19:49.913+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.061 seconds
[2023-03-07T08:20:20.182+0000] {processor.py:153} INFO - Started process (PID=10719) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:20:20.183+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:20:20.184+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:20:20.184+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:20:20.213+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:20:20.212+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:20:20.213+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:20:20.237+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.059 seconds
[2023-03-07T08:20:50.414+0000] {processor.py:153} INFO - Started process (PID=10746) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:20:50.415+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:20:50.416+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:20:50.416+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:20:50.448+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:20:50.446+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:20:50.448+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:20:50.475+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.066 seconds
[2023-03-07T08:21:20.706+0000] {processor.py:153} INFO - Started process (PID=10773) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:21:20.708+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:21:20.709+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:21:20.709+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:21:20.743+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:21:20.742+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:21:20.743+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:21:20.770+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.069 seconds
[2023-03-07T08:21:50.939+0000] {processor.py:153} INFO - Started process (PID=10813) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:21:50.940+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:21:50.941+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:21:50.941+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:21:50.970+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:21:50.969+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:21:50.970+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:21:50.994+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.060 seconds
[2023-03-07T08:22:21.247+0000] {processor.py:153} INFO - Started process (PID=10841) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:22:21.249+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:22:21.249+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:22:21.249+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:22:21.278+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:22:21.277+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:22:21.278+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:22:21.298+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.056 seconds
[2023-03-07T08:22:51.593+0000] {processor.py:153} INFO - Started process (PID=10881) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:22:51.594+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:22:51.595+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:22:51.595+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:22:51.624+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:22:51.623+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:22:51.624+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:22:51.644+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.056 seconds
[2023-03-07T08:23:21.910+0000] {processor.py:153} INFO - Started process (PID=10909) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:23:21.910+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:23:21.911+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:23:21.911+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:23:21.939+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:23:21.938+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:23:21.940+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:23:21.961+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.056 seconds
[2023-03-07T08:23:52.213+0000] {processor.py:153} INFO - Started process (PID=10938) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:23:52.216+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:23:52.217+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:23:52.217+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:23:52.246+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:23:52.245+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:23:52.246+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:23:52.269+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.062 seconds
[2023-03-07T08:24:22.426+0000] {processor.py:153} INFO - Started process (PID=10978) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:24:22.427+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:24:22.428+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:24:22.428+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:24:22.457+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:24:22.456+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:24:22.457+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:24:22.480+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.059 seconds
[2023-03-07T08:24:52.631+0000] {processor.py:153} INFO - Started process (PID=11005) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:24:52.633+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:24:52.634+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:24:52.634+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:24:52.663+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:24:52.662+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:24:52.663+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:24:52.686+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.059 seconds
[2023-03-07T08:25:22.920+0000] {processor.py:153} INFO - Started process (PID=11031) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:25:22.921+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:25:22.922+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:25:22.922+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:25:22.954+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:25:22.953+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:25:22.954+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:25:22.975+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.059 seconds
[2023-03-07T08:25:53.133+0000] {processor.py:153} INFO - Started process (PID=11069) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:25:53.134+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:25:53.135+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:25:53.135+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:25:53.166+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:25:53.165+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:25:53.167+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:25:53.196+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.070 seconds
[2023-03-07T08:26:23.347+0000] {processor.py:153} INFO - Started process (PID=11096) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:26:23.348+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:26:23.349+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:26:23.349+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:26:23.376+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:26:23.376+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:26:23.377+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:26:23.402+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.060 seconds
[2023-03-07T08:26:53.678+0000] {processor.py:153} INFO - Started process (PID=11138) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:26:53.680+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:26:53.680+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:26:53.680+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:26:53.709+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:26:53.708+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:26:53.709+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:26:53.733+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.060 seconds
[2023-03-07T08:27:24.057+0000] {processor.py:153} INFO - Started process (PID=11166) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:27:24.058+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:27:24.059+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:27:24.059+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:27:24.088+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:27:24.087+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:27:24.088+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:27:24.113+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.060 seconds
[2023-03-07T08:27:54.349+0000] {processor.py:153} INFO - Started process (PID=11203) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:27:54.351+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:27:54.352+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:27:54.352+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:27:54.391+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:27:54.390+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:27:54.392+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:27:54.415+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.072 seconds
[2023-03-07T08:28:24.668+0000] {processor.py:153} INFO - Started process (PID=11234) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:28:24.670+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:28:24.671+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:28:24.670+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:28:24.699+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:28:24.698+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:28:24.699+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:28:24.722+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.060 seconds
[2023-03-07T08:28:54.966+0000] {processor.py:153} INFO - Started process (PID=11262) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:28:54.967+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:28:54.968+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:28:54.968+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:28:54.998+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:28:54.997+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:28:54.998+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:28:55.019+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.060 seconds
[2023-03-07T08:29:25.324+0000] {processor.py:153} INFO - Started process (PID=11302) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:29:25.326+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:29:25.327+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:29:25.326+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:29:25.355+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:29:25.353+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:29:25.355+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:29:25.381+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.062 seconds
[2023-03-07T08:29:55.649+0000] {processor.py:153} INFO - Started process (PID=11330) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:29:55.650+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:29:55.651+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:29:55.651+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:29:55.679+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:29:55.678+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:29:55.679+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:29:55.699+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.054 seconds
[2023-03-07T08:30:25.949+0000] {processor.py:153} INFO - Started process (PID=11366) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:30:25.951+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:30:25.952+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:30:25.952+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:30:25.992+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:30:25.991+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:30:25.993+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:30:26.021+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.080 seconds
[2023-03-07T08:30:56.326+0000] {processor.py:153} INFO - Started process (PID=11396) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:30:56.327+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:30:56.328+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:30:56.328+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:30:56.368+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:30:56.366+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:30:56.368+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:30:56.392+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.071 seconds
[2023-03-07T08:31:26.643+0000] {processor.py:153} INFO - Started process (PID=11424) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:31:26.645+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:31:26.646+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:31:26.646+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:31:26.674+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:31:26.673+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:31:26.674+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:31:26.695+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.056 seconds
[2023-03-07T08:31:56.957+0000] {processor.py:153} INFO - Started process (PID=11460) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:31:56.958+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:31:56.959+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:31:56.959+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:31:57.000+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:31:56.998+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:31:57.000+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:31:57.027+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.076 seconds
[2023-03-07T08:32:27.181+0000] {processor.py:153} INFO - Started process (PID=11491) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:32:27.183+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:32:27.184+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:32:27.184+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:32:27.216+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:32:27.215+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:32:27.216+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:32:27.239+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.062 seconds
[2023-03-07T08:32:57.464+0000] {processor.py:153} INFO - Started process (PID=11517) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:32:57.465+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:32:57.466+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:32:57.466+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:32:57.495+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:32:57.494+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:32:57.495+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:32:57.515+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.056 seconds
[2023-03-07T08:33:27.671+0000] {processor.py:153} INFO - Started process (PID=11556) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:33:27.673+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:33:27.674+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:33:27.673+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:33:27.713+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:33:27.712+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:33:27.714+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:33:27.742+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.079 seconds
[2023-03-07T08:33:57.952+0000] {processor.py:153} INFO - Started process (PID=11583) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:33:57.953+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:33:57.954+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:33:57.953+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:33:57.981+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:33:57.980+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:33:57.981+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:33:58.005+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.059 seconds
[2023-03-07T08:34:28.175+0000] {processor.py:153} INFO - Started process (PID=11610) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:34:28.177+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:34:28.178+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:34:28.178+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:34:28.206+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:34:28.205+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:34:28.207+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:34:28.228+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.058 seconds
[2023-03-07T08:34:58.379+0000] {processor.py:153} INFO - Started process (PID=11650) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:34:58.380+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:34:58.381+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:34:58.381+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:34:58.409+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:34:58.408+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:34:58.410+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:34:58.435+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.061 seconds
[2023-03-07T08:35:28.585+0000] {processor.py:153} INFO - Started process (PID=11677) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:35:28.587+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:35:28.588+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:35:28.588+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:35:28.617+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:35:28.616+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:35:28.617+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:35:28.642+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.061 seconds
[2023-03-07T08:35:58.873+0000] {processor.py:153} INFO - Started process (PID=11717) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:35:58.874+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:35:58.875+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:35:58.875+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:35:58.915+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:35:58.914+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:35:58.916+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:35:58.945+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.077 seconds
[2023-03-07T08:36:29.208+0000] {processor.py:153} INFO - Started process (PID=11745) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:36:29.210+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:36:29.211+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:36:29.211+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:36:29.240+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:36:29.239+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:36:29.241+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:36:29.262+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.058 seconds
[2023-03-07T08:36:59.531+0000] {processor.py:153} INFO - Started process (PID=11772) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:36:59.532+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:36:59.533+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:36:59.533+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:36:59.561+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:36:59.560+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:36:59.562+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:36:59.583+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.056 seconds
[2023-03-07T08:37:29.876+0000] {processor.py:153} INFO - Started process (PID=11811) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:37:29.878+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:37:29.879+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:37:29.878+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:37:29.909+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:37:29.908+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:37:29.910+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:37:29.930+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.059 seconds
[2023-03-07T08:38:00.179+0000] {processor.py:153} INFO - Started process (PID=11839) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:38:00.180+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:38:00.181+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:38:00.181+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:38:00.209+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:38:00.208+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:38:00.210+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:38:00.230+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.055 seconds
[2023-03-07T08:38:30.502+0000] {processor.py:153} INFO - Started process (PID=11867) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:38:30.504+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:38:30.505+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:38:30.504+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:38:30.534+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:38:30.533+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:38:30.534+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:38:30.554+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.057 seconds
[2023-03-07T08:39:00.861+0000] {processor.py:153} INFO - Started process (PID=11907) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:39:00.862+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:39:00.863+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:39:00.863+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:39:00.893+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:39:00.892+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:39:00.893+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:39:00.919+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.063 seconds
[2023-03-07T08:39:31.210+0000] {processor.py:153} INFO - Started process (PID=11934) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:39:31.212+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:39:31.213+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:39:31.213+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:39:31.244+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:39:31.243+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:39:31.244+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:39:31.265+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.059 seconds
[2023-03-07T08:40:01.502+0000] {processor.py:153} INFO - Started process (PID=11973) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:40:01.503+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:40:01.504+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:40:01.504+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:40:01.533+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:40:01.532+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:40:01.533+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:40:01.554+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.057 seconds
[2023-03-07T08:40:31.698+0000] {processor.py:153} INFO - Started process (PID=12004) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:40:31.700+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:40:31.701+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:40:31.701+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:40:31.730+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:40:31.729+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:40:31.730+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:40:31.753+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.060 seconds
[2023-03-07T08:41:01.978+0000] {processor.py:153} INFO - Started process (PID=12032) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:41:01.980+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:41:01.981+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:41:01.981+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:41:02.011+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:41:02.010+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:41:02.012+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:41:02.036+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.063 seconds
[2023-03-07T08:41:32.328+0000] {processor.py:153} INFO - Started process (PID=12072) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:41:32.330+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:41:32.331+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:41:32.330+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:41:32.366+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:41:32.365+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:41:32.367+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:41:32.389+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.066 seconds
[2023-03-07T08:42:02.656+0000] {processor.py:153} INFO - Started process (PID=12099) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:42:02.657+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:42:02.658+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:42:02.658+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:42:02.686+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:42:02.685+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:42:02.687+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:42:02.709+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.058 seconds
[2023-03-07T08:42:32.948+0000] {processor.py:153} INFO - Started process (PID=12136) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:42:32.950+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:42:32.951+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:42:32.951+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:42:32.982+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:42:32.981+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:42:32.983+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:42:33.012+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.068 seconds
[2023-03-07T08:43:03.267+0000] {processor.py:153} INFO - Started process (PID=12166) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:43:03.268+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:43:03.269+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:43:03.269+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:43:03.298+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:43:03.297+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:43:03.298+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:43:03.322+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.059 seconds
[2023-03-07T08:43:33.580+0000] {processor.py:153} INFO - Started process (PID=12194) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:43:33.581+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:43:33.582+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:43:33.582+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:43:33.611+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:43:33.610+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:43:33.611+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:43:33.633+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.057 seconds
[2023-03-07T08:44:03.891+0000] {processor.py:153} INFO - Started process (PID=12233) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:44:03.892+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:44:03.893+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:44:03.893+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:44:03.933+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:44:03.931+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:44:03.933+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:44:03.958+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.072 seconds
[2023-03-07T08:44:34.227+0000] {processor.py:153} INFO - Started process (PID=12260) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:44:34.229+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:44:34.230+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:44:34.230+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:44:34.258+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:44:34.257+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:44:34.258+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:44:34.281+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.058 seconds
[2023-03-07T08:45:04.524+0000] {processor.py:153} INFO - Started process (PID=12296) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:45:04.525+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:45:04.526+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:45:04.526+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:45:04.556+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:45:04.554+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:45:04.556+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:45:04.581+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.061 seconds
[2023-03-07T08:45:34.884+0000] {processor.py:153} INFO - Started process (PID=12326) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:45:34.886+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:45:34.886+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:45:34.886+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:45:34.915+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:45:34.914+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:45:34.916+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:45:34.936+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.056 seconds
[2023-03-07T08:46:05.173+0000] {processor.py:153} INFO - Started process (PID=12353) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:46:05.175+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:46:05.176+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:46:05.176+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:46:05.205+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:46:05.204+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:46:05.205+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:46:05.225+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.056 seconds
[2023-03-07T08:46:35.496+0000] {processor.py:153} INFO - Started process (PID=12392) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:46:35.497+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:46:35.498+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:46:35.498+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:46:35.537+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:46:35.536+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:46:35.537+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:46:35.581+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.089 seconds
[2023-03-07T08:47:05.853+0000] {processor.py:153} INFO - Started process (PID=12420) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:47:05.855+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:47:05.856+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:47:05.856+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:47:05.885+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:47:05.884+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:47:05.885+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:47:05.908+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.061 seconds
[2023-03-07T08:47:36.174+0000] {processor.py:153} INFO - Started process (PID=12448) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:47:36.174+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:47:36.175+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:47:36.175+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:47:36.215+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:47:36.214+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:47:36.216+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:47:36.242+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.073 seconds
[2023-03-07T08:48:06.499+0000] {processor.py:153} INFO - Started process (PID=12486) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:48:06.502+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:48:06.503+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:48:06.502+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:48:06.531+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:48:06.530+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:48:06.531+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:48:06.552+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.058 seconds
[2023-03-07T08:48:36.808+0000] {processor.py:153} INFO - Started process (PID=12513) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:48:36.809+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:48:36.810+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:48:36.810+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:48:36.852+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:48:36.850+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:48:36.852+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:48:36.874+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.072 seconds
[2023-03-07T08:49:07.096+0000] {processor.py:153} INFO - Started process (PID=12552) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:49:07.098+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:49:07.099+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:49:07.099+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:49:07.129+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:49:07.128+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:49:07.130+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:49:07.153+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.061 seconds
[2023-03-07T08:49:37.426+0000] {processor.py:153} INFO - Started process (PID=12579) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:49:37.427+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:49:37.428+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:49:37.428+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:49:37.456+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:49:37.455+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:49:37.456+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:49:37.478+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.056 seconds
[2023-03-07T08:50:07.732+0000] {processor.py:153} INFO - Started process (PID=12615) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:50:07.734+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:50:07.734+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:50:07.734+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:50:07.763+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:50:07.762+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:50:07.763+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:50:07.786+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.058 seconds
[2023-03-07T08:50:38.044+0000] {processor.py:153} INFO - Started process (PID=12645) to work on /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:50:38.045+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2023-03-07T08:50:38.046+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:50:38.046+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:50:38.078+0000] {logging_mixin.py:137} INFO - [2023-03-07T08:50:38.077+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 8, in <module>
    from extract import extract_data
ModuleNotFoundError: No module named 'extract'
[2023-03-07T08:50:38.078+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2023-03-07T08:50:38.102+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.062 seconds
